### ISSUE TITLE
Different arrangement of directories

### ISSUE THREAD

**Issue by vinniefalco** [basiliscos/cpp-bredis#2]
To prevent conflicts with includes, it might be better if the library header files were located in a directory called `include/bredis` instead of `bredis/`.

This way, anyone who uses the library can simply clone the repository, and add
`-I{root}include/bredis` without worrying that they can pick up other includes (for example, trying to include `t/catch.hpp`).

**Comment by basiliscos** [comment]
Hi @vinniefalco ! 

Thank you very much! Sure, I'll follow your advises! Good advises - that's what I miss!

**Comment by basiliscos** [comment]
Done in `v0.02` :)
