### ISSUE TITLE
Consider (minimal) C++11 support

### ISSUE THREAD

**Issue by Al2Klimov** [basiliscos/cpp-bredis#32]
At the moment we (@Icinga) have to use this workaround to compile this lib:

```
#if __cplusplus < 201402L

#include <boost/type_traits/decay.hpp>
#include <boost/core/enable_if.hpp>

namespace std
{
using boost::decay_t;
using boost::enable_if_t;
}

#endif /* < C++14 */
```

It would be nice if we wouldn't have to.

**Comment by basiliscos** [comment]
Why not? Could you, please, make an PR?

**Comment by Al2Klimov** [comment]
I'm afraid the above quickfix is not enough.

**Comment by basiliscos** [comment]
I'll think about that a little bit on weekends, and I'll try to fix that.

**Comment by basiliscos** [comment]
I released a new `bredis` version, which now should support c++-11 (and it does, according to tests).  Let me know if you have any other issues.

And don't forget to star the project if you use it :)
