### ISSUE TITLE
Fix CMake warning while using CMake > 2.6.0

### ISSUE THREAD

**Issue by dhruvkakadiya** [basiliscos/cpp-bredis#34]
Include `cmake_minimum_required` check in `examples/CMakeLists.txt` to fix `CMP0000` policy.
```
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.14)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by dhruvkakadiya** [comment]
Maybe that's not necessary unless we try to use `examples/CMakeLists.txt` individually and try to build examples from that directly and not root directory. But then there are other boost packages and lots of other things would be missing so doesn't look worthy to fix this.

**Comment by basiliscos** [comment]
It was intended, that you don't need to `cmake` for bredis project at all: just copy it to your project and it's done. It already assumes usage of `boost::asio` and it does not pulls in addtional dependencies.
