### ISSUE TITLE
Doesn compile on WSL2 (Linux ubuntu gcc-8)

### ISSUE THREAD

**Issue by giorgiozoppi** [basiliscos/cpp-bredis#35]
![image](https://user-images.githubusercontent.com/27227826/66418659-d8399f80-ea02-11e9-879a-d30683060630.png) My current one is 1.65.1. Pretty urgent!

**Comment by basiliscos** [comment]
It seems you have an some old boost. I'll try to look on weekends. 

As the quick fix try to insert `enable_if_t` alias, like 

```
template< bool B, class T = void >
using enable_if_t = typename enable_if<B,T>::type;
```

**Comment by giorgiozoppi** [comment]
Ok please specify that with boost 1.71 compiling works in the docs. Thanks and in case of boost 1.65 or lower doesnt compile. Boost 1.71 is GA afaik.

**Comment by basiliscos** [comment]
Thank you. The minimum boost version is 1.69, I have mentioned that in the documentation (see https://github.com/basiliscos/cpp-bredis/pull/36 )
