### ISSUE TITLE
why do we need boost 1.69 ? how about boost 1.66

### ISSUE THREAD

**Issue by sunwake** [basiliscos/cpp-bredis#42]
what if i use boost 1.66 instead ?

**Comment by basiliscos** [comment]
Sure, you can try `1.66`, but some features like `coroutines` will probably not work.

**Comment by sunwake** [comment]
thank you . i am trying it

**Comment by basiliscos** [comment]
Sorry, to support modern coroutines I changed the boost version requirement to `v1.77` since bredis `v0.12`. You can use previous versions, if you need lower boost version

**Comment by sunwake** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到
