### ISSUE TITLE
Boost 1.74 and BOOST_ASIO_NO_DEPRECATED

### ISSUE THREAD

**Issue by amensel** [basiliscos/cpp-bredis#44]
asio_handler_invoke has been deprecated for a while, but in 1.74, they added compile-time detection for it if `BOOST_ASIO_NO_DEPRECATED` is defined.

This makes it impossible to use bredis with that flag, unfortunately, which is a must-have for certain Windows builds (it prevents a mis-detection of a specific constructor overload that leads to a crash).

**Comment by basiliscos** [comment]
Thank you again for your contribution. Your PR was merged and it is available in `v0.11`

**Comment by amensel** [comment]
Awesome! Glad to help out. Cheers!
