### ISSUE TITLE
cmake boost on windows

### ISSUE THREAD

**Issue by pasjkeee** [basiliscos/cpp-bredis#46]
Good day
I started learning cmake quite recently
And there there problems with conne
<img width="655" alt="sos" src="https://user-images.githubusercontent.com/72603507/95667457-2bdb4d80-0b6f-11eb-9a2c-b7c67ac759eb.png">
cting boost to cmake,how do I specify the desired directory? I work on windows

**Comment by basiliscos** [comment]
Hi, 

Search for `BOOST_ROOT`, and look for examples at https://github.com/basiliscos/cpp-bredis/blob/master/appveyor.yml
